# Generated by Django 3.2.13 on 2022-06-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sungjuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('kor', models.IntegerField(default=0)),
                ('eng', models.IntegerField(default=0)),
                ('mat', models.IntegerField(default=0)),
                ('sum', models.IntegerField(default=0)),
                ('avg', models.IntegerField(default=0)),
                ('grd', models.CharField(default='가', max_length=3)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
